services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: budgetbuddy
      MYSQL_USER: budgetbuddy
      MYSQL_PASSWORD: budgetbuddy123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - budgetbuddy_network

  api:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=budgetbuddy;Uid=budgetbuddy;Pwd=budgetbuddy123;
      - JWT_SECRET=2e351eb95b5162f503b22d4947c380224c8816c82492ae95424540b76086ad84
      - JWT_ISSUER=BudgetBuddy
      - JWT_AUDIENCE=BudgetBuddy
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - budgetbuddy_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - budgetbuddy_network

volumes:
  mysql_data:

networks:
  budgetbuddy_network:
    driver: bridge
